"""fix: Valor inicial da coluna de update

Revision ID: 60753f613a94
Revises: 32dfc8cf278e
Create Date: 2024-07-01 22:26:12.833985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60753f613a94'
down_revision: Union[str, None] = '32dfc8cf278e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
