"""feat: coluna de curso

Revision ID: 9a19bd25666b
Revises: 831b6cc67ed7
Create Date: 2024-07-01 20:29:29.111820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a19bd25666b'
down_revision: Union[str, None] = '831b6cc67ed7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('course', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'course')
    # ### end Alembic commands ###
